
#结尾记得加上"/"
IMG_SAVE_DIR = "D:/var/vip/"

[VPS1]

DB_HOST="127.0.0.1"

DB_PORT="3306"

DB_DATABASE="laravel-admin"

DB_USERNAME="root"

DB_PASSWORD="177678012"

[VPS2]

DB_HOST="127.0.0.1"

DB_PORT="3306"

DB_DATABASE="laravel-admin"

DB_USERNAME="root"

DB_PASSWORD="177678012"

